alert('IVORY IS A BIT TIRED OF USING THE SAME SCRIPTS');
alert('IVORY DECIDES HE WANTS TO PLAY A MINIGAME FOR YOU');
alert('YOU ACCEPT');
window.location.href = "https://ivorydevrimoalt.github.io/IVORYDEVRIMOIVORYDEVRIMOIVORYDEVRIMOIVORYDEVRIMOIVORYDEVRIMOIVORYDEVRIMOIVORYDEVRIMOIVORYDEVRIMO";
