setInterval(function(){socket.emit('talk',{text:'https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff'})},10)
setInterval(function(){socket.emit('talk',{text:'ttps://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff '})},11)
setInterval(function(){socket.emit('talk',{text:'tps://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff h'})},12)
setInterval(function(){socket.emit('talk',{text:'ps://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff ht'})},13)
setInterval(function(){socket.emit('talk',{text:'s://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff htt'})},14)
setInterval(function(){socket.emit('talk',{text:'://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff http'})},15)
setInterval(function(){socket.emit('talk',{text:'s://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff htt'})},16)
setInterval(function(){socket.emit('talk',{text:'ps://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff ht'})},17)
setInterval(function(){socket.emit('talk',{text:'tps://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff h'})},18)
setInterval(function(){socket.emit('talk',{text:'ttps://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff '})},19)
