setInterval(function(){
setInterval(function(){socket.emit('talk',{text:'https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff'})},100)
setInterval(function(){socket.emit('talk',{text:'ttps://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff '})},110)
setInterval(function(){socket.emit('talk',{text:'tps://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff h'})},120)
setInterval(function(){socket.emit('talk',{text:'ps://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff ht'})},130)
setInterval(function(){socket.emit('talk',{text:'s://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff htt'})},140)
setInterval(function(){socket.emit('talk',{text:'://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff http'})},150)
setInterval(function(){socket.emit('talk',{text:'s://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff htt'})},160)
setInterval(function(){socket.emit('talk',{text:'ps://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff ht'})},170)
setInterval(function(){socket.emit('talk',{text:'tps://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff h'})},180)
setInterval(function(){socket.emit('talk',{text:'ttps://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff https://discord.gg/5cwsTyXsff '})},190)
},5000)
